resnet56: &resnet56
  model_module: examples.vision.resnet_model:ResNet
  dataio_module: examples.vision.cifar10:CIFAR10

  batch_size: 256

  n_size: 9
  num_classes: 10

resnet110: &resnet110
  <<: *resnet56
  n_size: 18

bert: &bert
  model_module: rosetta.models.pretrained_bert:PretrainedBert
  dataio_module: rosetta.datasets.text.masked_text:MaskedTextDataIO

  train_data_path: ./tests/test_data/sonnets.txt
  eval_data_path: ./tests/test_data/sonnets.txt

  bert_config_file: ./examples/bert/config.json
  tokenizer_name: bert-base-cased

  hidden_size: 768
  vocab_size: 30522

  num_epochs: 100
