bert: &bert
  model_package: rosetta.models.pretrained_bert
  model_class: PretrainedBert
  dataio_package: rosetta.datasets.text.masked_text
  dataio_class: MaskedTextDataIO

  train_files:
    - ./tests/test_data/sonnets.txt
  
  eval_files:
    - ./tests/test_data/sonnets.txt

  bert_config_file: ./examples/bert/config.json
  tokenizer_name: bert-base-cased
  
  hidden_size: 768
  vocab_size: 30522
  
  num_epochs: 100

