bert: &bert
  model_package: rosetta.models.pretrained_bert
  model_class: PretrainedBert
  dataio_package: rosetta.datasets.text.masked_text
  dataio_class: MaskedTextDataIO

  train_files:
    - ./tests/test_data/sonnets.txt
  
  eval_files:
    - ./tests/test_data/sonnets.txt

  bert_config_file: ./examples/bert/config.json
  tokenizer_name: bert-base-cased
  
  hidden_size: 768
  vocab_size: 30522
  
  num_epochs: 100

resnet56: &resnet56
  model_package: examples.vision.resnet_model
  model_class: ResNet
  dataio_package: rosetta.datasets.vision.cifar10
  dataio_class: CIFAR10

  batch_size: 256
  
  n_size: 9
  num_classes: 10

