path:
    local: &local
      suffix_model_id: ''
      log_dir_prefix: './data/logs'
      model_dir_prefix: './data/models'
      # result_dir: './data/results'
      # summary_dir: './data/summaries'
  
default: &default
  <<: *local
  train_files: 
    - './datas/train_dataset'
  eval_files: 
    - './data/eval_dataset'
  batch_size: 32
  num_epochs: 10
  
  checkpoint_selector:
    eval_set: eval
    eval_metric: accuracy
    compare_fn: less
  
  data_loader_workers: 0
  shuffle_batches: 10
  prefetch_buffer_size: 5
  
  log_interval: 10
  save_summary_steps: 10
  save_checkpoints_steps: 500

  optimizer: AdamW
  learning_rate: 0.001  
  warmup_steps: 1000
  constant_steps: 2500
  lr_decay_method: exponential
  decay_steps: 1000
  decay_rate: 0.5
  weight_decay_rate: 0.01
  weight_averaging_decay: 0.9
  gradient_clip: true
  gradient_max_norm: 1.0

  dropout_rate: 0.1
