path:
    local: &local
      suffix_model_id: ''
      log_dir_prefix: './data/logs'
        
default: &default
  <<: *local
  train_data_path: './datas/train_dataset'
  eval_data_path: './data/eval_dataset'
  batch_size: 32
  num_epochs: 10
  
  checkpoint_selector:
    eval_set: eval
    eval_metric: accuracy
    higher_better: true
  
  dataloader_workers: 0
  
  log_interval: 10
  save_checkpoints_steps: 500

  optimizer: AdamW
  learning_rate: 1e-3  

  lr_warmup_steps: 1000
  lr_constant_steps: 1000
  lr_decay_method: exponential
  lr_decay_steps: 1000
  lr_decay_rate: 0.8
  
  weight_decay_rate: 0.01
  weight_averaging_decay: 0.9
  gradient_clip: true
  gradient_max_norm: 1.0

  dropout_rate: 0.1
